# Logging-Konfiguration
quarkus.log.level=INFO
quarkus.log.category."de.jklein".level=DEBUG

# Eigene Konfiguration für unsere HLF-Verbindung
hlf.mspId=TestMSP
hlf.certPath=test/path/cert.pem
hlf.keyPath=test/path/key.pem
hlf.channelName=testchannel
hlf.chaincodeName=testcc