spring.application.name=pharmalink

# ==================================
# Fabric Gateway Konfiguration
# ==================================
# Pfad zum Basisverzeichnis der Crypto-Materialien
# Passen Sie diesen Pfad an Ihre Umgebung an
fabric.mspId=Org1MSP
fabric.crypto.path=/Users/niklas/pharmalink/fabric-samples/test-network/
# MSP ID Ihrer Organisation

# Pfade zu den Zertifikaten und Schlüsseln (relativ zum crypto.path)
fabric.certPath=organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem
fabric.keyDirPath=organizations/peerOrganizations/org1.example.com/msp/keystore
fabric.tlsCertPath=organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
# Gateway Peer Endpunkt
fabric.peer.endpoint=node.d1.navine.tech:7051

# Channel und Chaincode
fabric.channelName=pharmalink
fabric.chaincodeName=pharmalink_chaincode_main