logging:
  level:
    root: INFO
    de.jklein.pharmalink: INFO
spring:
  application:
    name: pharmalink
  data:
    mongodb:
      uri: mongodb://user:user@localhost:27017/pharmalinkdb?authSource=admin
  thymeleaf:
    cache: false
    prefix: classpath:/web/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    enabled: true
app:
  initial-users:
    - username: admin
      password: $2a$10$nZYgNvdSmcF6Nw.AtWBwLeapUQrLxRTZSkXWlOaD/xZyvFw8DkBke
      roles:
        - ROLE_USER
        - ROLE_ADMIN

jwt:
  secret: a3NkYXNkODMxMm5Bc2RqMm5yQXNkbWtkbGZOQURmOTIzZWtKQVNEa21scGdBRGFTRGc=
  expiration: 3600000

system:
  benutzername: admin
  passwort: admin123

springdoc:
  info:
    title: Pharmalink API
    description: API-Dokumentation für die Pharmalink Lieferkettenanwendung auf Hyperledger Fabric.
    path: /api/swagger
  api-docs:
    path: /api/api-docs
actor:
  bezeichnung: company2
fabric:
  msp-id: Org1MSP
  crypto-path: /Users/niklas/pharmalink/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com
  cert-path: users/hersteller-user1@org1.example.com/msp/signcerts
  key-dir-path: users/hersteller-user1@org1.example.com/msp/keystore
  tls-cert-path: peers/peer0.org1.example.com/tls/ca.crt
  peer:
    endpoint: node.d1.navine.tech:7051
    override-auth: peer0.org1.example.com
  channel-name: pharmalink
  chaincode-name: pharmalink_chaincode_main
ipfs:
  email: ipfs@example.com
  ipfs-link: null
  host: localhost
  port: 5001
  timeout: 3