# Logging-Konfiguration
quarkus.log.level=INFO
quarkus.log.category."de.jklein".level=DEBUG

# Eigene Konfiguration für unsere HLF-Verbindung
hlf.mspId=TestMSP
hlf.certPath=test/path/cert.pem
hlf.keyPath=test/path/key.pem
hlf.channelName=testchannel
hlf.chaincodeName=testcc

# Swagger und OpenAPI
quarkus.swagger-ui.path=/api-swagger
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/api-docs
quarkus.smallrye-openapi.info-title=PharmaLink API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.resteasy-reactive.path=/api