version: '3.7'

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-dev
    restart: always
    volumes:
      - ipfs_data:/data/ipfs
    ports:
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8081:8080"
      - "4001:4001/tcp"
      - "4001:4001/udp"
    networks:
      - dev-net

  postgres:
    image: postgres:16
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: entwickler
      POSTGRES_PASSWORD: entwickler
      POSTGRES_DB: pharmalinkdb
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-net

volumes:
  postgres_data:
  ipfs_data:

networks:
  pharmalink-net:
    driver: bridge