version: '3.7'
volumes:
  pgdata: {}
  walletstore: {}

networks:
  fabric_test:
    external: true

services:
  explorerdb:
    image: ghcr.io/hyperledger-labs/explorer-db:latest
    container_name: explorerdb
    hostname: explorerdb
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-q", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fabric_test
      -
  explorer:
    image: ghcr.io/hyperledger-labs/explorer:latest
    container_name: explorer
    environment:
      - DATABASE_HOST=explorerdb
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
      - PORT=8080
    volumes:
      - ./explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./explorer/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../fabric-samples/test-network/organizations:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8088:8080
    depends_on:
      explorerdb:
        condition: service_healthy
    networks:
      - fabric_test
