version: '3.7'

services:
  pharmalink-app:
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: pharmalink
    ports:
      - "8080:8080"
    volumes:
      - ../fabric-samples/test-network/organizations:/fabric-crypto/organizations:ro
      - ./pharmalink/config.yaml:/etc/pharmalink/config.yaml:ro
    restart: unless-stopped