version: '3.7'

services:
  pharmalink-app:
    image: ghcr.io/niklasjavier/pharmalink:latest
    container_name: pharmalink
    ports:
      # API-Zugang für Ihren Rechner (Host)
      - "8080:8080"
    volumes:
      - ../fabric-samples/test-network/organizations:/fabric-crypto/organizations:ro
      - ./pharmalink/config.yaml:/etc/pharmalink/config.yaml:ro
    networks:
      - pharmalink-net
    restart: unless-stopped
    # NEU: Umgebungsvariablen für die Datenbankverbindung
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pharmalinkdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_node
    restart: always
    volumes:
      - ./pharmalink/ipfs/ipfs_data:/data/ipfs
      - ./pharmalink/ipfs/staging:/export
    ports:
      # Swarm-Port für die Kommunikation mit anderen IPFS-Peers im Internet
      - "4001:4001/tcp"
      - "4001:4001/udp"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8081:8080"
    networks:
      - pharmalink-net

  postgres:
    image: postgres:17.5-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: pharmalinkdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pharmalink-net

networks:
  pharmalink-net:
    driver: bridge

volumes:
  postgres-data: