springdoc:
  info:
    title: "Pharmalink API"
    description: "API-Dokumentation für die Pharmalink Lieferkettenanwendung auf Hyperledger Fabric."
    path: "/api/swagger"
  api-docs:
    path: "/api/api-docs"

system:
  benutzername: "admin"
  passwort: "admin123"

spring:
  application:
    name: "pharmalink"
  datasource:
    url: "jdbc:postgresql://host.docker.internal:5432/pharmalinkdb"
    username: "user"
    password: "user"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
  thymeleaf:
    prefix: "classpath:/web/"
    suffix: ".html"
    mode: "HTML"
    cache: true
    check-template-location: true
    enabled: true
    encoding: "UTF-8"

app:
  initial-users:
    - username: "admin"
      password: "$2a$10$nZYgNvdSmcF6Nw.AtWBwLeapUQrLxRTZSkXWlOaD/xZyvFw8DkBke"
      roles:
        - "ROLE_USER"
        - "ROLE_ADMIN"

actor:
  bezeichnung: "company2"

fabric:
  msp-id: "Org1MSP"
  crypto-path: "/fabric-crypto/organizations/peerOrganizations/org1.example.com"
  cert-path: "users/hersteller-user1@org1.example.com/msp/signcerts"
  key-dir-path: "users/hersteller-user1@org1.example.com/msp/keystore"
  tls-cert-path: "peers/peer0.org1.example.com/tls/ca.crt"
  peer:
    endpoint: "node.d1.navine.tech:7051"
    override-auth: "peer0.org1.example.com"
  channel-name: "pharmalink"
  chaincode-name: "pharmalink_chaincode_main"

ipfs:
  email: "ipfs@example.com"
  ipfs-link: "12"
  host: "host.docker.internal"
  port: "5001"