# Logging-Konfiguration
quarkus.log.level=INFO
quarkus.log.category."de.jklein".level=DEBUG
quarkus.banner.path=banner.txt

# HLF
hlf.mspId=Org1MSP
hlf.certPath=organizations/peerOrganizations/de.navine.tech/users/User1@de.navine.tech/msp/signcerts/User1@de.navine.tech-cert.pem
hlf.keyPath=organizations/peerOrganizations/de.navine.tech/users/User1@de.navine.tech/msp/keystore/
hlf.channelName=pharmalink
hlf.chaincodeName=pharmalink_chaincode_main
fabric.gateway.connection.config.path=/pfad/zu/ihrem/connection.yaml

# Swagger und OpenAPI
quarkus.swagger-ui.path=/api-swagger
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/api-openapi
quarkus.smallrye-openapi.info-title=PharmaLink API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-license-name=Apache 2.0