# Copyright IBM Corp. All Rights Reserved. DEMO
#
# SPDX-License-Identifier: Apache-2.0

# Sektion: Organizations
Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: organizations/ordererOrganizations/navine.tech/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.navine.tech:7050

  - &RegDeOrg # Deutschland
    Name: RegDeMSP
    ID: RegDeMSP
    MSPDir: organizations/peerOrganizations/de.navine.tech/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RegDeMSP.admin', 'RegDeMSP.peer', 'RegDeMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RegDeMSP.admin', 'RegDeMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RegDeMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RegDeMSP.peer')"

  - &RegFrOrg # Frankreich
    Name: RegFrMSP
    ID: RegFrMSP
    MSPDir: organizations/peerOrganizations/fr.navine.tech/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RegFrMSP.admin', 'RegFrMSP.peer', 'OR('RegFrMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RegFrMSP.admin', 'RegFrMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RegFrMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RegFrMSP.peer')"

  - &RegBeOrg # Belgien
    Name: RegBeMSP
    ID: RegBeMSP
    MSPDir: organizations/peerOrganizations/be.navine.tech/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RegBeMSP.admin', 'RegBeMSP.peer', 'RegBeMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RegBeMSP.admin', 'RegBeMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RegBeMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RegBeMSP.peer')"

  - &RegEsOrg # Spanien
    Name: RegEsMSP
    ID: RegEsMSP
    MSPDir: organizations/peerOrganizations/es.navine.tech/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RegEsMSP.admin', 'RegEsMSP.peer', 'RegEsMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RegEsMSP.admin', 'RegEsMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RegEsMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RegEsMSP.peer')"

# SECTION: Consortiums
Consortiums:
  PharmaLinkConsortium: # Der Name deines Konsortiums
    Organizations:
      - *RegDeOrg
      - *RegFrOrg
      - *RegBeOrg
      - *RegEsOrg

# SECTION: Capabilities
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

# SECTION: Application
Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

# SECTION: Orderer
Orderer: &OrdererDefaults
  Addresses:
    - orderer.navine.tech:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

# SECTION: Channel
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

# SECTION: Profile
Profiles:
  ChannelUsingRaft:
    <<: *ChannelDefaults
    Consortium: PharmaLinkConsortium # MUSS mit dem Namen übereinstimmen, den du in der Consortiums-Sektion gewählt hast!
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer.navine.tech
            Port: 7050
            ClientTLSCert: organizations/ordererOrganizations/navine.tech/orderers/orderer.navine.tech/tls/server.crt
            ServerTLSCert: organizations/ordererOrganizations/navine.tech/orderers/orderer.navine.tech/tls/server.crt
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *RegDeOrg
        - *RegFrOrg
        - *RegBeOrg
        - *RegEsOrg
      Capabilities: *ApplicationCapabilities